version: "3.6"
services:

  vpn:
    image: itsdaspecialk/pia-openvpn
    container_name: pia
    cap_add:
      - NET_ADMIN
    network_mode: server_default
    dns:
     - 209.222.18.222
     - 209.222.18.218
    environment:
      REGION: 'Sweden'
      USERNAME: '?????'
      PASSWORD: '?????'
    restart: always

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    depends_on:
      - vpn
    environment:
      PGID: 1000
      PUID: 1000
      TZ: 'Europe/London'
    network_mode: service:vpn
#    ports:
#      - 9091:9091
#      - 51413:51413
    volumes:
      - ./transmission/:/config
      - /media/content/downloads/:/downloads
      - /media/content/watch/:/watch
    restart: unless-stopped
    stdin_open: true
    tty: true

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
      - vpn
    network_mode: service:vpn
    volumes:
      - ./jackett/:/config
      - /media/content/watch/:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: 1000
      PUID: 1000
      TZ: 'Europe/London'
#    ports:
#      - 9117:9117
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
#    depends_on:
#      - transmission
    networks:
      - vpn-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
#    depends_on:
#      - transmission
    networks:
      - vpn-network
    volumes:
      - ./sonarr/:/config
      - /media/content/TV/:/tv
      - /media/content/downloads/complete/:/downloads/complete/
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: 1000
      PUID: 1000
      TZ: 'Europe/London'
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
#    depends_on:
#      - transmission
    networks:
      - vpn-network
    volumes:
      - ./radarr/:/config
      - /media/content/Movies/:/movies
      - /media/content/downloads/complete/:/downloads/complete/
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: 1000
      PUID: 1000
      TZ: 'Europe/London'
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  vpn-network:
    external:
      name: server_default