version: "3.7"

services:
  pia_transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    container_name: pia_transmission
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "8989:8989" #sonarr
      - "9117:9117" #jackett
      - "7878:7878" #radarr
      - "8686:8686" #lidarr
      - "5299:5299" #lazyLib
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - media_server
    env_file:
      - .env_openvpn
    volumes:
      - /opt/transmission:/data/transmission-home
      - /media/content/downloads:/data
      - /media/content/watch:/data/watch

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
      - pia_transmission
    restart: always
    env_file:
      - .env
    volumes:
      - /opt/jackett/:/config
      - /media/content/watch/:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: "service:pia_transmission"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /opt/sonarr/:/config
      - /media/content/TV/:/tv
      - /media/content/downloads/completed/:/downloads/complete/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env-hidden
    restart: unless-stopped
    network_mode: "service:pia_transmission"


  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/radarr/:/config
      - /media/content/Movies/:/movies
      - /media/content/downloads/completed/:/downloads/complete/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env-hidden
    restart: unless-stopped
    network_mode: "service:pia_transmission"

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    volumes:
      - /opt/lidarr/:/config
      - /media/content/Music/:/music
      - /media/content/downloads/completed/:/downloads/complete/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env-hidden
    restart: unless-stopped
    network_mode: "service:pia_transmission"

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    env_file:
      - .env-hidden
    volumes:
      - /opt/lazylibrarian/:/config
      - /media/content/downloads/completed/:/downloads/complete/
      - /media/content/Books/:/books
      - /media/content/Audioooks/:/audiobooks
    restart: unless-stopped
    network_mode: "service:pia_transmission"

networks:
  media_server:
    driver: bridge
